name: test-backend

on:
  push:
    branches: [ "main" ]      
    paths:
      - 'microservice/**'
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'microservice/**'
      - 'backend/**'

jobs:
  test-django:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.5
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
